version: '3.4'

services:

    db:
      image: 'mcr.microsoft.com/mssql/server'
      container_name: TodoDB
      environment:
          - ACCEPT_EULA=Y
          - 'SA_PASSWORD=<YourStrong@Passw0rd>'
      ports:
          - '1444:1433'

    todoapp.api:
      image: ${DOCKER_REGISTRY-}todoappapi
      ports:
          - '8080:80'
      build:
        context: .
        dockerfile: TodoApp.Api/Dockerfile
